<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PokemonTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('pokemons')->delete();

        DB::table('pokemons')->insert(array(
            0 =>
            array(
                'name' => 'Bulbasaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '6.90',
                'height' => '0.70',
                'hp' => 45,
                'attack' => 49,
                'defense' => 49,
                'is_legendary' => 0,
                'photo' => 'bulbasaur.png',
            ),
            1 =>
            array(
                'name' => 'Ivysaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '13.00',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 62,
                'defense' => 63,
                'is_legendary' => 0,
                'photo' => 'ivysaur.png',
            ),
            2 =>
            array(
                'name' => 'Venusaur',
                'species' => 'Seed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '100.00',
                'height' => '2.00',
                'hp' => 80,
                'attack' => 100,
                'defense' => 123,
                'is_legendary' => 0,
                'photo' => 'venusaur.png',
            ),
            3 =>
            array(
                'name' => 'Charmander',
                'species' => 'Lizard Pokemon',
                'primary_type' => 'Fire',
                'weight' => '8.50',
                'height' => '0.60',
                'hp' => 39,
                'attack' => 52,
                'defense' => 43,
                'is_legendary' => 0,
                'photo' => 'charmander.png',
            ),
            4 =>
            array(
                'name' => 'Charmeleon',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '19.00',
                'height' => '1.10',
                'hp' => 58,
                'attack' => 64,
                'defense' => 58,
                'is_legendary' => 0,
                'photo' => 'charmeleon.png',
            ),
            5 =>
            array(
                'name' => 'Charizard',
                'species' => 'Flame Pokemon',
                'primary_type' => 'Fire',
                'weight' => '90.50',
                'height' => '1.70',
                'hp' => 78,
                'attack' => 104,
                'defense' => 78,
                'is_legendary' => 0,
                'photo' => 'charizard.png',
            ),
            6 =>
            array(
                'name' => 'Squirtle',
                'species' => 'Tiny Turtle Pokemon',
                'primary_type' => 'Water',
                'weight' => '9.00',
                'height' => '0.50',
                'hp' => 44,
                'attack' => 48,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'squirtle.png',
            ),
            7 =>
            array(
                'name' => 'Wartortle',
                'species' => 'Turtle Pokemon',
                'primary_type' => 'Water',
                'weight' => '22.50',
                'height' => '1.00',
                'hp' => 59,
                'attack' => 63,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'wartortle.png',
            ),
            8 =>
            array(
                'name' => 'Blastoise',
                'species' => 'Shellfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '85.50',
                'height' => '1.60',
                'hp' => 79,
                'attack' => 103,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'blastoise.png',
            ),
            9 =>
            array(
                'name' => 'Caterpie',
                'species' => 'Worm Pokemon',
                'primary_type' => 'Bug',
                'weight' => '2.90',
                'height' => '0.30',
                'hp' => 45,
                'attack' => 30,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'caterpie.png',
            ),
            10 =>
            array(
                'name' => 'Metapod',
                'species' => 'Cocoon Pokemon',
                'primary_type' => 'Bug',
                'weight' => '9.90',
                'height' => '0.70',
                'hp' => 50,
                'attack' => 20,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'metapod.png',
            ),
            11 =>
            array(
                'name' => 'Butterfree',
                'species' => 'Butterfly Pokemon',
                'primary_type' => 'Bug',
                'weight' => '32.00',
                'height' => '1.10',
                'hp' => 60,
                'attack' => 45,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'butterfree.png',
            ),
            12 =>
            array(
                'name' => 'Weedle',
                'species' => 'Hairy Pokemon',
                'primary_type' => 'Bug',
                'weight' => '3.20',
                'height' => '0.30',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'weedle.png',
            ),
            13 =>
            array(
                'name' => 'Kakuna',
                'species' => 'Cocoon Pokemon',
                'primary_type' => 'Bug',
                'weight' => '10.00',
                'height' => '0.60',
                'hp' => 45,
                'attack' => 25,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'kakuna.png',
            ),
            14 =>
            array(
                'name' => 'Beedrill',
                'species' => 'Poison Bee Pokemon',
                'primary_type' => 'Bug',
                'weight' => '29.50',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 150,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'beedrill.png',
            ),
            15 =>
            array(
                'name' => 'Pidgey',
                'species' => 'Tiny Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '1.80',
                'height' => '0.30',
                'hp' => 40,
                'attack' => 45,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'pidgey.png',
            ),
            16 =>
            array(
                'name' => 'Pidgeotto',
                'species' => 'Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '30.00',
                'height' => '1.10',
                'hp' => 63,
                'attack' => 60,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'pidgeotto.png',
            ),
            17 =>
            array(
                'name' => 'Pidgeot',
                'species' => 'Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '39.50',
                'height' => '1.50',
                'hp' => 83,
                'attack' => 80,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'pidgeot.png',
            ),
            18 =>
            array(
                'name' => 'Rattata',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Normal',
                'weight' => '3.75',
                'height' => '0.30',
                'hp' => 30,
                'attack' => 56,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'rattata.png',
            ),
            19 =>
            array(
                'name' => 'Raticate',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Normal',
                'weight' => '18.50',
                'height' => '0.70',
                'hp' => 75,
                'attack' => 71,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'raticate.png',
            ),
            20 =>
            array(
                'name' => 'Spearow',
                'species' => 'Tiny Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '2.00',
                'height' => '0.30',
                'hp' => 40,
                'attack' => 60,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'spearow.png',
            ),
            21 =>
            array(
                'name' => 'Fearow',
                'species' => 'Beak Pokemon',
                'primary_type' => 'Normal',
                'weight' => '38.00',
                'height' => '1.20',
                'hp' => 65,
                'attack' => 90,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'fearow.png',
            ),
            22 =>
            array(
                'name' => 'Ekans',
                'species' => 'Snake Pokemon',
                'primary_type' => 'Poison',
                'weight' => '6.90',
                'height' => '2.00',
                'hp' => 35,
                'attack' => 60,
                'defense' => 44,
                'is_legendary' => 0,
                'photo' => 'ekans.png',
            ),
            23 =>
            array(
                'name' => 'Arbok',
                'species' => 'Cobra Pokemon',
                'primary_type' => 'Poison',
                'weight' => '65.00',
                'height' => '3.50',
                'hp' => 60,
                'attack' => 95,
                'defense' => 69,
                'is_legendary' => 0,
                'photo' => 'arbok.png',
            ),
            24 =>
            array(
                'name' => 'Pikachu',
                'species' => 'Mouse Pokemon',
                'primary_type' => 'Electric',
                'weight' => '6.00',
                'height' => '0.40',
                'hp' => 35,
                'attack' => 55,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'pikachu.png',
            ),
            25 =>
            array(
                'name' => 'Nidoran ♂',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => '7.00',
                'height' => '0.40',
                'hp' => 55,
                'attack' => 47,
                'defense' => 52,
                'is_legendary' => 0,
                'photo' => 'nidoran-m.png',
            ),
            26 =>
            array(
                'name' => 'Nidorina',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => '20.00',
                'height' => '0.80',
                'hp' => 70,
                'attack' => 62,
                'defense' => 67,
                'is_legendary' => 0,
                'photo' => 'nidorina.png',
            ),
            27 =>
            array(
                'name' => 'Nidoqueen',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Poison',
                'weight' => '60.00',
                'height' => '1.30',
                'hp' => 90,
                'attack' => 92,
                'defense' => 87,
                'is_legendary' => 0,
                'photo' => 'nidoqueen.png',
            ),
            28 =>
            array(
                'name' => 'Nidoran ♀',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => '9.00',
                'height' => '0.50',
                'hp' => 46,
                'attack' => 57,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'nidoran-f.png',
            ),
            29 =>
            array(
                'name' => 'Nidorino',
                'species' => 'Poison Pin Pokemon',
                'primary_type' => 'Poison',
                'weight' => '19.50',
                'height' => '0.90',
                'hp' => 61,
                'attack' => 72,
                'defense' => 57,
                'is_legendary' => 0,
                'photo' => 'nidorino.png',
            ),
            30 =>
            array(
                'name' => 'Nidoking',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Poison',
                'weight' => '62.00',
                'height' => '1.40',
                'hp' => 81,
                'attack' => 102,
                'defense' => 77,
                'is_legendary' => 0,
                'photo' => 'nidoking.png',
            ),
            31 =>
            array(
                'name' => 'Clefairy',
                'species' => 'Fairy Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '7.50',
                'height' => '0.60',
                'hp' => 70,
                'attack' => 45,
                'defense' => 48,
                'is_legendary' => 0,
                'photo' => 'clefairy.png',
            ),
            32 =>
            array(
                'name' => 'Clefable',
                'species' => 'Fairy Pokemon',
                'primary_type' => 'Fairy',
                'weight' => '40.00',
                'height' => '1.30',
                'hp' => 95,
                'attack' => 70,
                'defense' => 73,
                'is_legendary' => 0,
                'photo' => 'clefable.png',
            ),
            33 =>
            array(
                'name' => 'Jigglypuff',
                'species' => 'Balloon Pokemon',
                'primary_type' => 'Normal',
                'weight' => '5.50',
                'height' => '0.50',
                'hp' => 115,
                'attack' => 45,
                'defense' => 20,
                'is_legendary' => 0,
                'photo' => 'jigglypuff.png',
            ),
            34 =>
            array(
                'name' => 'Wigglytuff',
                'species' => 'Balloon Pokemon',
                'primary_type' => 'Normal',
                'weight' => '12.00',
                'height' => '1.00',
                'hp' => 140,
                'attack' => 70,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'wigglytuff.png',
            ),
            35 =>
            array(
                'name' => 'Zubat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => '7.50',
                'height' => '0.80',
                'hp' => 40,
                'attack' => 45,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'zubat.png',
            ),
            36 =>
            array(
                'name' => 'Golbat',
                'species' => 'Bat Pokemon',
                'primary_type' => 'Poison',
                'weight' => '55.00',
                'height' => '1.60',
                'hp' => 75,
                'attack' => 80,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'golbat.png',
            ),
            37 =>
            array(
                'name' => 'Oddish',
                'species' => 'Weed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '5.40',
                'height' => '0.50',
                'hp' => 45,
                'attack' => 50,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'oddish.png',
            ),
            38 =>
            array(
                'name' => 'Gloom',
                'species' => 'Weed Pokemon',
                'primary_type' => 'Grass',
                'weight' => '8.60',
                'height' => '0.80',
                'hp' => 60,
                'attack' => 65,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'gloom.png',
            ),
            39 =>
            array(
                'name' => 'Vileplume',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '18.60',
                'height' => '1.20',
                'hp' => 75,
                'attack' => 80,
                'defense' => 85,
                'is_legendary' => 0,
                'photo' => 'vileplume.png',
            ),
            40 =>
            array(
                'name' => 'Paras',
                'species' => 'Mushroom Pokemon',
                'primary_type' => 'Bug',
                'weight' => '5.40',
                'height' => '0.30',
                'hp' => 35,
                'attack' => 70,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'paras.png',
            ),
            41 =>
            array(
                'name' => 'Parasect',
                'species' => 'Mushroom Pokemon',
                'primary_type' => 'Bug',
                'weight' => '29.50',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 95,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'parasect.png',
            ),
            42 =>
            array(
                'name' => 'Venonat',
                'species' => 'Insect Pokemon',
                'primary_type' => 'Bug',
                'weight' => '30.00',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 55,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'venonat.png',
            ),
            43 =>
            array(
                'name' => 'Venomoth',
                'species' => 'Poison Moth Pokemon',
                'primary_type' => 'Bug',
                'weight' => '12.50',
                'height' => '1.50',
                'hp' => 70,
                'attack' => 65,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'venomoth.png',
            ),
            44 =>
            array(
                'name' => 'Psyduck',
                'species' => 'Duck Pokemon',
                'primary_type' => 'Water',
                'weight' => '19.60',
                'height' => '0.80',
                'hp' => 50,
                'attack' => 52,
                'defense' => 48,
                'is_legendary' => 0,
                'photo' => 'psyduck.png',
            ),
            45 =>
            array(
                'name' => 'Golduck',
                'species' => 'Duck Pokemon',
                'primary_type' => 'Water',
                'weight' => '76.60',
                'height' => '1.70',
                'hp' => 80,
                'attack' => 82,
                'defense' => 78,
                'is_legendary' => 0,
                'photo' => 'golduck.png',
            ),
            46 =>
            array(
                'name' => 'Mankey',
                'species' => 'Pig Monkey Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '28.00',
                'height' => '0.50',
                'hp' => 40,
                'attack' => 80,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'mankey.png',
            ),
            47 =>
            array(
                'name' => 'Primeape',
                'species' => 'Pig Monkey Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '32.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 105,
                'defense' => 60,
                'is_legendary' => 0,
                'photo' => 'primeape.png',
            ),
            48 =>
            array(
                'name' => 'Growlithe',
                'species' => 'Puppy Pokemon',
                'primary_type' => 'Fire',
                'weight' => '19.00',
                'height' => '0.70',
                'hp' => 55,
                'attack' => 70,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'growlithe.png',
            ),
            49 =>
            array(
                'name' => 'Arcanine',
                'species' => 'Legendary Pokemon',
                'primary_type' => 'Fire',
                'weight' => '155.00',
                'height' => '1.90',
                'hp' => 90,
                'attack' => 110,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'arcanine.png',
            ),
            50 =>
            array(
                'name' => 'Poliwag',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '12.40',
                'height' => '0.60',
                'hp' => 40,
                'attack' => 50,
                'defense' => 40,
                'is_legendary' => 0,
                'photo' => 'poliwag.png',
            ),
            51 =>
            array(
                'name' => 'Poliwhirl',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '20.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 65,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'poliwhirl.png',
            ),
            52 =>
            array(
                'name' => 'Poliwrath',
                'species' => 'Tadpole Pokemon',
                'primary_type' => 'Water',
                'weight' => '54.00',
                'height' => '1.30',
                'hp' => 90,
                'attack' => 95,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'poliwrath.png',
            ),
            53 =>
            array(
                'name' => 'Abra',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '19.50',
                'height' => '0.90',
                'hp' => 25,
                'attack' => 20,
                'defense' => 15,
                'is_legendary' => 0,
                'photo' => 'abra.png',
            ),
            54 =>
            array(
                'name' => 'Kadabra',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '56.50',
                'height' => '1.30',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'kadabra.png',
            ),
            55 =>
            array(
                'name' => 'Alakazam',
                'species' => 'Psi Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '48.00',
                'height' => '1.50',
                'hp' => 55,
                'attack' => 50,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'alakazam.png',
            ),
            56 =>
            array(
                'name' => 'Machop',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '19.50',
                'height' => '0.80',
                'hp' => 70,
                'attack' => 80,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'machop.png',
            ),
            57 =>
            array(
                'name' => 'Machoke',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '70.50',
                'height' => '1.50',
                'hp' => 80,
                'attack' => 100,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'machoke.png',
            ),
            58 =>
            array(
                'name' => 'Machamp',
                'species' => 'Superpower Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '130.00',
                'height' => '1.60',
                'hp' => 90,
                'attack' => 130,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'machamp.png',
            ),
            59 =>
            array(
                'name' => 'Bellsprout',
                'species' => 'Flower Pokemon',
                'primary_type' => 'Grass',
                'weight' => '4.00',
                'height' => '0.70',
                'hp' => 50,
                'attack' => 75,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'bellsprout.png',
            ),
            60 =>
            array(
                'name' => 'Weepinbell',
                'species' => 'Flycatcher Pokemon',
                'primary_type' => 'Grass',
                'weight' => '6.40',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 90,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'weepinbell.png',
            ),
            61 =>
            array(
                'name' => 'Victreebel',
                'species' => 'Flycatcher Pokemon',
                'primary_type' => 'Grass',
                'weight' => '15.50',
                'height' => '1.70',
                'hp' => 80,
                'attack' => 105,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'victreebel.png',
            ),
            62 =>
            array(
                'name' => 'Tentacool',
                'species' => 'Jellyfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '45.50',
                'height' => '0.90',
                'hp' => 40,
                'attack' => 40,
                'defense' => 35,
                'is_legendary' => 0,
                'photo' => 'tentacool.png',
            ),
            63 =>
            array(
                'name' => 'Tentacruel',
                'species' => 'Jellyfish Pokemon',
                'primary_type' => 'Water',
                'weight' => '55.00',
                'height' => '1.60',
                'hp' => 80,
                'attack' => 70,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'tentacruel.png',
            ),
            64 =>
            array(
                'name' => 'Ponyta',
                'species' => 'Fire Horse Pokemon',
                'primary_type' => 'Fire',
                'weight' => '30.00',
                'height' => '1.00',
                'hp' => 50,
                'attack' => 85,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'ponyta.png',
            ),
            65 =>
            array(
                'name' => 'Rapidash',
                'species' => 'Fire Horse Pokemon',
                'primary_type' => 'Fire',
                'weight' => '95.00',
                'height' => '1.70',
                'hp' => 65,
                'attack' => 100,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'rapidash.png',
            ),
            66 =>
            array(
                'name' => 'Slowpoke',
                'species' => 'Dopey Pokemon',
                'primary_type' => 'Water',
                'weight' => '36.00',
                'height' => '1.20',
                'hp' => 90,
                'attack' => 65,
                'defense' => 65,
                'is_legendary' => 0,
                'photo' => 'slowpoke.png',
            ),
            67 =>
            array(
                'name' => 'Slowbro',
                'species' => 'Hermit Crab Pokemon',
                'primary_type' => 'Water',
                'weight' => '78.50',
                'height' => '1.60',
                'hp' => 95,
                'attack' => 75,
                'defense' => 180,
                'is_legendary' => 0,
                'photo' => 'slowbro.png',
            ),
            68 =>
            array(
                'name' => 'Magnemite',
                'species' => 'Magnet Pokemon',
                'primary_type' => 'Electric',
                'weight' => '6.00',
                'height' => '0.30',
                'hp' => 25,
                'attack' => 35,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'magnemite.png',
            ),
            69 =>
            array(
                'name' => 'Magneton',
                'species' => 'Magnet Pokemon',
                'primary_type' => 'Electric',
                'weight' => '60.00',
                'height' => '1.00',
                'hp' => 50,
                'attack' => 60,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'magneton.png',
            ),
            70 =>
            array(
                'name' => 'Farfetch\'d',
                'species' => 'Wild Duck Pokemon',
                'primary_type' => 'Normal',
                'weight' => '15.00',
                'height' => '0.80',
                'hp' => 52,
                'attack' => 90,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'farfetchd.png',
            ),
            71 =>
            array(
                'name' => 'Doduo',
                'species' => 'Twin Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '39.20',
                'height' => '1.40',
                'hp' => 35,
                'attack' => 85,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'doduo.png',
            ),
            72 =>
            array(
                'name' => 'Dodrio',
                'species' => 'Triple Bird Pokemon',
                'primary_type' => 'Normal',
                'weight' => '85.20',
                'height' => '1.80',
                'hp' => 60,
                'attack' => 110,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'dodrio.png',
            ),
            73 =>
            array(
                'name' => 'Seel',
                'species' => 'Sea Lion Pokemon',
                'primary_type' => 'Water',
                'weight' => '90.00',
                'height' => '1.10',
                'hp' => 65,
                'attack' => 45,
                'defense' => 55,
                'is_legendary' => 0,
                'photo' => 'seel.png',
            ),
            74 =>
            array(
                'name' => 'Dewgong',
                'species' => 'Sea Lion Pokemon',
                'primary_type' => 'Water',
                'weight' => '120.00',
                'height' => '1.70',
                'hp' => 90,
                'attack' => 70,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'dewgong.png',
            ),
            75 =>
            array(
                'name' => 'Shellder',
                'species' => 'Bivalve Pokemon',
                'primary_type' => 'Water',
                'weight' => '4.00',
                'height' => '0.30',
                'hp' => 30,
                'attack' => 65,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'shellder.png',
            ),
            76 =>
            array(
                'name' => 'Cloyster',
                'species' => 'Bivalve Pokemon',
                'primary_type' => 'Water',
                'weight' => '132.50',
                'height' => '1.50',
                'hp' => 50,
                'attack' => 95,
                'defense' => 180,
                'is_legendary' => 0,
                'photo' => 'cloyster.png',
            ),
            77 =>
            array(
                'name' => 'Gastly',
                'species' => 'Gas Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '0.10',
                'height' => '1.30',
                'hp' => 30,
                'attack' => 35,
                'defense' => 30,
                'is_legendary' => 0,
                'photo' => 'gastly.png',
            ),
            78 =>
            array(
                'name' => 'Haunter',
                'species' => 'Gas Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '0.10',
                'height' => '1.60',
                'hp' => 45,
                'attack' => 50,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'haunter.png',
            ),
            79 =>
            array(
                'name' => 'Gengar',
                'species' => 'Shadow Pokemon',
                'primary_type' => 'Ghost',
                'weight' => '40.50',
                'height' => '1.50',
                'hp' => 60,
                'attack' => 65,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'gengar.png',
            ),
            80 =>
            array(
                'name' => 'Onix',
                'species' => 'Rock Snake Pokemon',
                'primary_type' => 'Rock',
                'weight' => '210.00',
                'height' => '8.80',
                'hp' => 35,
                'attack' => 45,
                'defense' => 160,
                'is_legendary' => 0,
                'photo' => 'onix.png',
            ),
            81 =>
            array(
                'name' => 'Drowzee',
                'species' => 'Hypnosis Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '32.40',
                'height' => '1.00',
                'hp' => 60,
                'attack' => 48,
                'defense' => 45,
                'is_legendary' => 0,
                'photo' => 'drowzee.png',
            ),
            82 =>
            array(
                'name' => 'Hypno',
                'species' => 'Hypnosis Pokemon',
                'primary_type' => 'Psychic',
                'weight' => '75.60',
                'height' => '1.60',
                'hp' => 85,
                'attack' => 73,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'hypno.png',
            ),
            83 =>
            array(
                'name' => 'Krabby',
                'species' => 'River Crab Pokemon',
                'primary_type' => 'Water',
                'weight' => '6.50',
                'height' => '0.40',
                'hp' => 30,
                'attack' => 105,
                'defense' => 90,
                'is_legendary' => 0,
                'photo' => 'krabby.png',
            ),
            84 =>
            array(
                'name' => 'Kingler',
                'species' => 'Pincer Pokemon',
                'primary_type' => 'Water',
                'weight' => '60.00',
                'height' => '1.30',
                'hp' => 55,
                'attack' => 130,
                'defense' => 115,
                'is_legendary' => 0,
                'photo' => 'kingler.png',
            ),
            85 =>
            array(
                'name' => 'Voltorb',
                'species' => 'Ball Pokemon',
                'primary_type' => 'Electric',
                'weight' => '10.40',
                'height' => '0.50',
                'hp' => 40,
                'attack' => 30,
                'defense' => 50,
                'is_legendary' => 0,
                'photo' => 'voltorb.png',
            ),
            86 =>
            array(
                'name' => 'Electrode',
                'species' => 'Ball Pokemon',
                'primary_type' => 'Electric',
                'weight' => '66.60',
                'height' => '1.20',
                'hp' => 60,
                'attack' => 50,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'electrode.png',
            ),
            87 =>
            array(
                'name' => 'Exeggcute',
                'species' => 'Egg Pokemon',
                'primary_type' => 'Grass',
                'weight' => '2.50',
                'height' => '0.40',
                'hp' => 60,
                'attack' => 40,
                'defense' => 80,
                'is_legendary' => 0,
                'photo' => 'exeggcute.png',
            ),
            88 =>
            array(
                'name' => 'Cubone',
                'species' => 'Lonely Pokemon',
                'primary_type' => 'Ground',
                'weight' => '6.50',
                'height' => '0.40',
                'hp' => 50,
                'attack' => 50,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'cubone.png',
            ),
            89 =>
            array(
                'name' => 'Hitmonlee',
                'species' => 'Kicking Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '49.80',
                'height' => '1.50',
                'hp' => 50,
                'attack' => 120,
                'defense' => 53,
                'is_legendary' => 0,
                'photo' => 'hitmonlee.png',
            ),
            90 =>
            array(
                'name' => 'Hitmonchan',
                'species' => 'Punching Pokemon',
                'primary_type' => 'Fighting',
                'weight' => '50.20',
                'height' => '1.40',
                'hp' => 50,
                'attack' => 105,
                'defense' => 79,
                'is_legendary' => 0,
                'photo' => 'hitmonchan.png',
            ),
            91 =>
            array(
                'name' => 'Lickitung',
                'species' => 'Licking Pokemon',
                'primary_type' => 'Normal',
                'weight' => '65.50',
                'height' => '1.20',
                'hp' => 90,
                'attack' => 55,
                'defense' => 75,
                'is_legendary' => 0,
                'photo' => 'lickitung.png',
            ),
            92 =>
            array(
                'name' => 'Koffing',
                'species' => 'Poison Gas Pokemon',
                'primary_type' => 'Poison',
                'weight' => '1.00',
                'height' => '0.60',
                'hp' => 40,
                'attack' => 65,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'koffing.png',
            ),
            93 =>
            array(
                'name' => 'Weezing',
                'species' => 'Poison Gas Pokemon',
                'primary_type' => 'Poison',
                'weight' => '9.50',
                'height' => '1.20',
                'hp' => 65,
                'attack' => 90,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'weezing.png',
            ),
            94 =>
            array(
                'name' => 'Rhyhorn',
                'species' => 'Spikes Pokemon',
                'primary_type' => 'Ground',
                'weight' => '115.00',
                'height' => '1.00',
                'hp' => 80,
                'attack' => 85,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'rhyhorn.png',
            ),
            95 =>
            array(
                'name' => 'Rhydon',
                'species' => 'Drill Pokemon',
                'primary_type' => 'Ground',
                'weight' => '120.00',
                'height' => '1.90',
                'hp' => 105,
                'attack' => 130,
                'defense' => 120,
                'is_legendary' => 0,
                'photo' => 'rhydon.png',
            ),
            96 =>
            array(
                'name' => 'Chansey',
                'species' => 'Egg Pokemon',
                'primary_type' => 'Normal',
                'weight' => '34.60',
                'height' => '1.10',
                'hp' => 250,
                'attack' => 5,
                'defense' => 5,
                'is_legendary' => 0,
                'photo' => 'chansey.png',
            ),
            97 =>
            array(
                'name' => 'Tangela',
                'species' => 'Vine Pokemon',
                'primary_type' => 'Grass',
                'weight' => '35.00',
                'height' => '1.00',
                'hp' => 65,
                'attack' => 55,
                'defense' => 115,
                'is_legendary' => 0,
                'photo' => 'tangela.png',
            ),
            98 =>
            array(
                'name' => 'Kangaskhan',
                'species' => 'Parent Pokemon',
                'primary_type' => 'Normal',
                'weight' => '80.00',
                'height' => '2.20',
                'hp' => 105,
                'attack' => 125,
                'defense' => 100,
                'is_legendary' => 0,
                'photo' => 'kangaskhan.png',
            ),
            99 =>
            array(
                'name' => 'Horsea',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Water',
                'weight' => '8.00',
                'height' => '0.40',
                'hp' => 30,
                'attack' => 40,
                'defense' => 70,
                'is_legendary' => 0,
                'photo' => 'horsea.png',
            ),
            100 =>
            array(
                'name' => 'Seadra',
                'species' => 'Dragon Pokemon',
                'primary_type' => 'Water',
                'weight' => '25.00',
                'height' => '1.20',
                'hp' => 55,
                'attack' => 65,
                'defense' => 95,
                'is_legendary' => 0,
                'photo' => 'seadra.png',
            ),
        ));
    }
}
